name: Unzip And Push Source

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Extract ZIP
        run: |
          unzip -o OThemezip.zip -d temp

          # 如果多一层目录，自动移动出来
          if [ -d "temp/OThemezip" ]; then
            cp -r temp/OThemezip/* .
            cp -r temp/OThemezip/.[!.]* . 2>/dev/null || true
          else
            cp -r temp/* .
          fi

          rm -rf temp
          rm -f OThemezip.zip

          ls -la


      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          git commit -m "Auto extract source from zip" || echo "No changes"

          git push
